# adk_agent_app/tools/gatekeeper_tools.py
from typing import Any, Dict

from google.adk.tools import FunctionTool, ToolContext
from google.cloud import firestore

from ..config import FIRESTORE_APP_DB, PROJECT_ID, logger


def _get_firestore_client() -> firestore.Client:
    """Lazy initializer to prevent gRPC fork / event loop conflicts."""
    return firestore.Client(project=PROJECT_ID, database=FIRESTORE_APP_DB)


async def is_registered_user(user_id: str, tool_context: ToolContext) -> Dict[str, Any]:
    """Checks the database to verify if a given User ID is registered and hydrates session state.

    Args:
        user_id: The unique identifier of the user (e.g., 'usr_12345').

    Returns:
        Dict[str, Any]: A dictionary containing execution details and memory status.
            - status (str): The outcome of the check ('success', 'not_found', or 'error').
            - exists (bool): True if the user exists in Firestore, False otherwise.
            - verified_user_id (str, optional): The user ID verified (only present on 'success').
            - message (str): A descriptive message explaining the result for the agent to communicate.
    """
    try:
        db = _get_firestore_client()
        user_ref = db.collection("users").document(user_id)
        user_doc = user_ref.get()

        if not user_doc.exists:
            return {
                "status": "not_found",
                "exists": False,
                "message": (
                    f"User ID '{user_id}' does not exist. Please tell them that the user "
                    "does not exist and ask if they would like to register."
                ),
            }

        user_data = user_doc.to_dict() or {}
        vehicle = user_data.get("vehicle", {})

        # Hydrate active ADK Session Memory via ToolContext
        state = tool_context.state
        state["user:name"] = user_data.get("full_name") or user_data.get("name", "")
        state["user:email"] = user_data.get("email", "")
        state["user:preferred_language"] = user_data.get("preferred_language", "English")
        state["user:culinary_preferences"] = user_data.get("culinary_preferences", [])
        state["user:vehicle_type"] = vehicle.get(
            "vehicle_type", user_data.get("vehicle_type", "Gasoline")
        )

        # Save verified ID key in session scope (for multi-turn tools) and temp: scope
        state["verified_user_id"] = user_id
        state["temp:verified_user_id"] = user_id
        state["workflow_step"] = "user_verified"

        logger.info(
            f"Verified user '{user_id}' and hydrated profile into active ADK session memory."
        )

        return {
            "status": "success",
            "exists": True,
            "verified_user_id": user_id,
            "message": f"User '{user_id}' verified successfully. Profile loaded into working memory.",
        }

    except Exception as e:
        logger.error(f"Error in is_registered_user: {e}", exc_info=True)
        return {
            "status": "error",
            "message": f"A database error occurred while verifying the user: {str(e)}",
        }


# Wrap as an ADK FunctionTool (ADK automatically excludes `tool_context` from the schema sent to Gemini)
# Note: The tool name exposed to the LLM is `func.__name__` ('is_registered_user'),
# not the Python variable name ('is_registered_user_tool').
is_registered_user_tool = FunctionTool(is_registered_user)

## 4. Pull out the autogenerated definition attribute
## ADK formats this to map directly to Gemini's FunctionDeclaration API object
# tool_definition = is_registered_user_tool._get_declaration()

## 5. Convert the definition object to a clean JSON string
## Depending on the exact ADK patch, definition might be a dict or a Pydantic object.
## We handle both cases gracefully here:
# if hasattr(tool_definition, "model_dump"):
#     json_schema = tool_definition.model_dump()
# elif hasattr(tool_definition, "to_dict"):
#     json_schema = tool_definition.to_dict()
# else:
#     json_schema = tool_definition
# print(json.dumps(json_schema, indent=2))
